# Generated by Django 4.2.3 on 2023-09-21 13:40

import MAIN.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='empleado',
        ),
        migrations.AddField(
            model_name='departamento',
            name='token',
            field=models.CharField(default=MAIN.models.Departamento.generate_token, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MAIN.departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MAIN.departamento'),
        ),
    ]
