# Generated by Django 4.2.3 on 2023-09-25 13:43

import MAIN.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_solicitudes_email_solicitudes_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(null=True, upload_to=MAIN.models.generate_path_file),
        ),
    ]
