# Generated by Django 4.2.3 on 2023-09-25 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='almacen', to=settings.AUTH_USER_MODEL),
        ),
    ]
