# Generated by Django 4.2.3 on 2023-09-25 14:37

import MAIN.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_alter_almacen_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='delivered_estimated',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(upload_to=MAIN.models.generate_path_file),
        ),
    ]
