# Generated by Django 4.2.3 on 2023-09-28 20:15

import MAIN.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_producto_delivered_estimated_producto_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='almacen',
            name='recinto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='almacen', to='MAIN.recinto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(null=True, upload_to=MAIN.models.generate_path_file),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='status',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Entregada', 'Entregada')], default='En proceso', max_length=50),
        ),
    ]
